"""Generate the scan list from the game's own variable table.

Only Integer and Boolean variables are taken. Floats and vectors carry
continuous quantities that change every frame, which would bury the state
transitions the scan exists to find.

Usage: gen_state_vars.py <anim-variables.tsv> <out.h>
"""
import sys

STATE_TYPES = {"Integer": "VAR_INT", "Boolean": "VAR_BOOL"}

HEADER = """#pragma once

// Generated by tools/gen_state_vars.py from docs/anim-variables.tsv.
// Do not edit by hand.

#define SF360_STATE_VARS(X) \\
"""


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)

    rows = []
    with open(sys.argv[1], encoding="utf-8") as f:
        for line in f:
            name, _, kind = line.strip().partition("\t")
            if kind in STATE_TYPES:
                rows.append((name, STATE_TYPES[kind]))

    with open(sys.argv[2], "w", encoding="utf-8") as out:
        out.write(HEADER)
        out.write(" \\\n".join(f'    X("{n}", {t})' for n, t in rows))
        out.write("\n")

    print(f"{sys.argv[2]}: {len(rows)} variables")
    return 0


if __name__ == "__main__":
    sys.exit(main())
